# Generated by Django 3.2.19 on 2023-05-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='平台')),
                ('dir_name', models.CharField(max_length=64, unique=True, verbose_name='代码文件名')),
                ('host', models.CharField(max_length=512, verbose_name='URL')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '平台',
                'verbose_name_plural': '平台',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16, unique=True, verbose_name='IP')),
                ('system', models.CharField(choices=[('windows', 'windows'), ('mac', 'mac'), ('liunx', 'liunx')], db_index=True, max_length=32, verbose_name='系统')),
                ('server_name', models.CharField(max_length=64, unique=True, verbose_name='服务器名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
            },
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(max_length=64, verbose_name='爬虫名')),
                ('spider_code', models.CharField(max_length=64, verbose_name='爬虫编码')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='可用状态')),
                ('params_restrict', models.JSONField(blank=True, null=True, verbose_name='参数约定')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprier_manage.platform', verbose_name='平台')),
            ],
            options={
                'verbose_name': '爬虫',
                'verbose_name_plural': '爬虫',
                'unique_together': {('platform', 'spider_code')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='手机号')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='可用状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sprier_manage.platform', verbose_name='平台')),
            ],
            options={
                'verbose_name': '账号',
                'verbose_name_plural': '账号',
                'unique_together': {('platform', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未知任务名称', max_length=32, verbose_name='任务名称')),
                ('frequency', models.CharField(default='未知频次', max_length=16, verbose_name='频次')),
                ('status', models.IntegerField(choices=[(0, '待定'), (1, '启用'), (10, '弃用'), (11, '暂时不可用')], default=0, verbose_name='启用')),
                ('params_text', models.CharField(default='daily', max_length=128, verbose_name='参数映射')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='参数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprier_manage.account', verbose_name='账号')),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprier_manage.spider', verbose_name='爬虫')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'unique_together': {('account', 'spider', 'name')},
            },
        ),
    ]
